version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  python-38: &test-template
    docker:
      - image: cimg/python:3.8-node
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PERCY_ENABLE: 0
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Write job name
          command: echo $CIRCLE_JOB > circlejob.txt

      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "dev-requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r dev-requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "dev-requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
          paths:
          - "venv"

      - run:
          name: Flake8
          command: |
            . venv/bin/activate
            flake8 dash_auth setup.py

      - run:
          name: Test with pytest
          command: |
            . venv/bin/activate
            pytest --headless

  python-312:
    <<: *test-template
    docker:
      - image: cimg/python:3.12-node
        auth:
          username: dashautomation
          password: $DASH_PAT_DOCKERHUB
        environment:
          PERCY_ENABLE: 0

workflows:
  test:
    jobs:
      - python-38
      - python-312
